//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clerk
    {
        public int ClerkKey { get; set; }
        public string ClerkFName { get; set; }
        public string ClerkLName { get; set; }
        public string ClerkPassword { get; set; }
        public bool IfManager { get; set; }
    }
}
