//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DataBaseMMModel", "FK_AmountPeopleInShelter_Shelters", "Shelters", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.Shelter), "AmountPeopleInShelter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.AmountPeopleInShelter), true)]

#endregion

namespace DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataBaseMMEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataBaseMMEntities object using the connection string found in the 'DataBaseMMEntities' section of the application configuration file.
        /// </summary>
        public DataBaseMMEntities() : base("name=DataBaseMMEntities", "DataBaseMMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataBaseMMEntities object.
        /// </summary>
        public DataBaseMMEntities(string connectionString) : base(connectionString, "DataBaseMMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataBaseMMEntities object.
        /// </summary>
        public DataBaseMMEntities(EntityConnection connection) : base(connection, "DataBaseMMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AmountPeopleInShelter> AmountPeopleInShelters
        {
            get
            {
                if ((_AmountPeopleInShelters == null))
                {
                    _AmountPeopleInShelters = base.CreateObjectSet<AmountPeopleInShelter>("AmountPeopleInShelters");
                }
                return _AmountPeopleInShelters;
            }
        }
        private ObjectSet<AmountPeopleInShelter> _AmountPeopleInShelters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clerk> Clerks
        {
            get
            {
                if ((_Clerks == null))
                {
                    _Clerks = base.CreateObjectSet<Clerk>("Clerks");
                }
                return _Clerks;
            }
        }
        private ObjectSet<Clerk> _Clerks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shelter> Shelters
        {
            get
            {
                if ((_Shelters == null))
                {
                    _Shelters = base.CreateObjectSet<Shelter>("Shelters");
                }
                return _Shelters;
            }
        }
        private ObjectSet<Shelter> _Shelters;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AmountPeopleInShelters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAmountPeopleInShelters(AmountPeopleInShelter amountPeopleInShelter)
        {
            base.AddObject("AmountPeopleInShelters", amountPeopleInShelter);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clerks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClerks(Clerk clerk)
        {
            base.AddObject("Clerks", clerk);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shelters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShelters(Shelter shelter)
        {
            base.AddObject("Shelters", shelter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataBaseMMModel", Name="AmountPeopleInShelter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AmountPeopleInShelter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AmountPeopleInShelter object.
        /// </summary>
        /// <param name="amountpplKey">Initial value of the AmountpplKey property.</param>
        /// <param name="shelterKey">Initial value of the ShelterKey property.</param>
        public static AmountPeopleInShelter CreateAmountPeopleInShelter(global::System.Int32 amountpplKey, global::System.Int32 shelterKey)
        {
            AmountPeopleInShelter amountPeopleInShelter = new AmountPeopleInShelter();
            amountPeopleInShelter.AmountpplKey = amountpplKey;
            amountPeopleInShelter.ShelterKey = shelterKey;
            return amountPeopleInShelter;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AmountpplKey
        {
            get
            {
                return _AmountpplKey;
            }
            set
            {
                if (_AmountpplKey != value)
                {
                    OnAmountpplKeyChanging(value);
                    ReportPropertyChanging("AmountpplKey");
                    _AmountpplKey = StructuralObject.SetValidValue(value, "AmountpplKey");
                    ReportPropertyChanged("AmountpplKey");
                    OnAmountpplKeyChanged();
                }
            }
        }
        private global::System.Int32 _AmountpplKey;
        partial void OnAmountpplKeyChanging(global::System.Int32 value);
        partial void OnAmountpplKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShelterKey
        {
            get
            {
                return _ShelterKey;
            }
            set
            {
                OnShelterKeyChanging(value);
                ReportPropertyChanging("ShelterKey");
                _ShelterKey = StructuralObject.SetValidValue(value, "ShelterKey");
                ReportPropertyChanged("ShelterKey");
                OnShelterKeyChanged();
            }
        }
        private global::System.Int32 _ShelterKey;
        partial void OnShelterKeyChanging(global::System.Int32 value);
        partial void OnShelterKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AmountPPLSpeDH
        {
            get
            {
                return _AmountPPLSpeDH;
            }
            set
            {
                OnAmountPPLSpeDHChanging(value);
                ReportPropertyChanging("AmountPPLSpeDH");
                _AmountPPLSpeDH = StructuralObject.SetValidValue(value, "AmountPPLSpeDH");
                ReportPropertyChanged("AmountPPLSpeDH");
                OnAmountPPLSpeDHChanged();
            }
        }
        private Nullable<global::System.Int32> _AmountPPLSpeDH;
        partial void OnAmountPPLSpeDHChanging(Nullable<global::System.Int32> value);
        partial void OnAmountPPLSpeDHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, "Time");
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Time;
        partial void OnTimeChanging(Nullable<global::System.TimeSpan> value);
        partial void OnTimeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataBaseMMModel", "FK_AmountPeopleInShelter_Shelters", "Shelters")]
        public Shelter Shelter
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shelter>("DataBaseMMModel.FK_AmountPeopleInShelter_Shelters", "Shelters").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shelter>("DataBaseMMModel.FK_AmountPeopleInShelter_Shelters", "Shelters").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Shelter> ShelterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shelter>("DataBaseMMModel.FK_AmountPeopleInShelter_Shelters", "Shelters");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Shelter>("DataBaseMMModel.FK_AmountPeopleInShelter_Shelters", "Shelters", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataBaseMMModel", Name="Clerk")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clerk : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clerk object.
        /// </summary>
        /// <param name="clerkKey">Initial value of the ClerkKey property.</param>
        /// <param name="clerkFName">Initial value of the ClerkFName property.</param>
        /// <param name="clerkLName">Initial value of the ClerkLName property.</param>
        /// <param name="clerkPassword">Initial value of the ClerkPassword property.</param>
        /// <param name="ifManager">Initial value of the IfManager property.</param>
        public static Clerk CreateClerk(global::System.Int32 clerkKey, global::System.String clerkFName, global::System.String clerkLName, global::System.String clerkPassword, global::System.Boolean ifManager)
        {
            Clerk clerk = new Clerk();
            clerk.ClerkKey = clerkKey;
            clerk.ClerkFName = clerkFName;
            clerk.ClerkLName = clerkLName;
            clerk.ClerkPassword = clerkPassword;
            clerk.IfManager = ifManager;
            return clerk;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClerkKey
        {
            get
            {
                return _ClerkKey;
            }
            set
            {
                if (_ClerkKey != value)
                {
                    OnClerkKeyChanging(value);
                    ReportPropertyChanging("ClerkKey");
                    _ClerkKey = StructuralObject.SetValidValue(value, "ClerkKey");
                    ReportPropertyChanged("ClerkKey");
                    OnClerkKeyChanged();
                }
            }
        }
        private global::System.Int32 _ClerkKey;
        partial void OnClerkKeyChanging(global::System.Int32 value);
        partial void OnClerkKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClerkFName
        {
            get
            {
                return _ClerkFName;
            }
            set
            {
                OnClerkFNameChanging(value);
                ReportPropertyChanging("ClerkFName");
                _ClerkFName = StructuralObject.SetValidValue(value, false, "ClerkFName");
                ReportPropertyChanged("ClerkFName");
                OnClerkFNameChanged();
            }
        }
        private global::System.String _ClerkFName;
        partial void OnClerkFNameChanging(global::System.String value);
        partial void OnClerkFNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClerkLName
        {
            get
            {
                return _ClerkLName;
            }
            set
            {
                OnClerkLNameChanging(value);
                ReportPropertyChanging("ClerkLName");
                _ClerkLName = StructuralObject.SetValidValue(value, false, "ClerkLName");
                ReportPropertyChanged("ClerkLName");
                OnClerkLNameChanged();
            }
        }
        private global::System.String _ClerkLName;
        partial void OnClerkLNameChanging(global::System.String value);
        partial void OnClerkLNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClerkPassword
        {
            get
            {
                return _ClerkPassword;
            }
            set
            {
                OnClerkPasswordChanging(value);
                ReportPropertyChanging("ClerkPassword");
                _ClerkPassword = StructuralObject.SetValidValue(value, false, "ClerkPassword");
                ReportPropertyChanged("ClerkPassword");
                OnClerkPasswordChanged();
            }
        }
        private global::System.String _ClerkPassword;
        partial void OnClerkPasswordChanging(global::System.String value);
        partial void OnClerkPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IfManager
        {
            get
            {
                return _IfManager;
            }
            set
            {
                OnIfManagerChanging(value);
                ReportPropertyChanging("IfManager");
                _IfManager = StructuralObject.SetValidValue(value, "IfManager");
                ReportPropertyChanged("IfManager");
                OnIfManagerChanged();
            }
        }
        private global::System.Boolean _IfManager;
        partial void OnIfManagerChanging(global::System.Boolean value);
        partial void OnIfManagerChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataBaseMMModel", Name="Shelter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shelter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shelter object.
        /// </summary>
        /// <param name="shelterKey">Initial value of the ShelterKey property.</param>
        /// <param name="latShelter">Initial value of the LatShelter property.</param>
        /// <param name="lngShelter">Initial value of the LngShelter property.</param>
        public static Shelter CreateShelter(global::System.Int32 shelterKey, global::System.Double latShelter, global::System.Double lngShelter)
        {
            Shelter shelter = new Shelter();
            shelter.ShelterKey = shelterKey;
            shelter.LatShelter = latShelter;
            shelter.LngShelter = lngShelter;
            return shelter;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShelterKey
        {
            get
            {
                return _ShelterKey;
            }
            set
            {
                if (_ShelterKey != value)
                {
                    OnShelterKeyChanging(value);
                    ReportPropertyChanging("ShelterKey");
                    _ShelterKey = StructuralObject.SetValidValue(value, "ShelterKey");
                    ReportPropertyChanged("ShelterKey");
                    OnShelterKeyChanged();
                }
            }
        }
        private global::System.Int32 _ShelterKey;
        partial void OnShelterKeyChanging(global::System.Int32 value);
        partial void OnShelterKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double LatShelter
        {
            get
            {
                return _LatShelter;
            }
            set
            {
                OnLatShelterChanging(value);
                ReportPropertyChanging("LatShelter");
                _LatShelter = StructuralObject.SetValidValue(value, "LatShelter");
                ReportPropertyChanged("LatShelter");
                OnLatShelterChanged();
            }
        }
        private global::System.Double _LatShelter;
        partial void OnLatShelterChanging(global::System.Double value);
        partial void OnLatShelterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double LngShelter
        {
            get
            {
                return _LngShelter;
            }
            set
            {
                OnLngShelterChanging(value);
                ReportPropertyChanging("LngShelter");
                _LngShelter = StructuralObject.SetValidValue(value, "LngShelter");
                ReportPropertyChanged("LngShelter");
                OnLngShelterChanged();
            }
        }
        private global::System.Double _LngShelter;
        partial void OnLngShelterChanging(global::System.Double value);
        partial void OnLngShelterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxPeople
        {
            get
            {
                return _MaxPeople;
            }
            set
            {
                OnMaxPeopleChanging(value);
                ReportPropertyChanging("MaxPeople");
                _MaxPeople = StructuralObject.SetValidValue(value, "MaxPeople");
                ReportPropertyChanged("MaxPeople");
                OnMaxPeopleChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxPeople;
        partial void OnMaxPeopleChanging(Nullable<global::System.Int32> value);
        partial void OnMaxPeopleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShelterDescription
        {
            get
            {
                return _ShelterDescription;
            }
            set
            {
                OnShelterDescriptionChanging(value);
                ReportPropertyChanging("ShelterDescription");
                _ShelterDescription = StructuralObject.SetValidValue(value, true, "ShelterDescription");
                ReportPropertyChanged("ShelterDescription");
                OnShelterDescriptionChanged();
            }
        }
        private global::System.String _ShelterDescription;
        partial void OnShelterDescriptionChanging(global::System.String value);
        partial void OnShelterDescriptionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataBaseMMModel", "FK_AmountPeopleInShelter_Shelters", "AmountPeopleInShelter")]
        public EntityCollection<AmountPeopleInShelter> AmountPeopleInShelters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AmountPeopleInShelter>("DataBaseMMModel.FK_AmountPeopleInShelter_Shelters", "AmountPeopleInShelter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AmountPeopleInShelter>("DataBaseMMModel.FK_AmountPeopleInShelter_Shelters", "AmountPeopleInShelter", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
