//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMMEntities : DbContext
    {
        public DBMMEntities()
            : base("name=DBMMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AmountPeopleInShelter> AmountPeopleInShelters { get; set; }
        public virtual DbSet<Clerk> Clerks { get; set; }
        public virtual DbSet<Shelter> Shelters { get; set; }
    }
}
